name: bloom-release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  bloom-release:
    runs-on: ubuntu-latest
    steps:
      - uses: at-wat/bloom-release-action@v0
        with:
          ros_distro: noetic humble iron jazzy
          github_token_bloom: ${{ secrets.GH_TOKEN_FOR_BLOOM_RELEASE }}
          github_user: jpbusch
          git_user: Jean-Pierre Busch
          git_email: jean-pierre.busch@ika.rwth-aachen.de
          release_repository_push_url: https://github.com/${{ github.repository }}-release.git
          open_pr: false