name: bloom-release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  bloom-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release ROS
        uses: at-wat/bloom-release-action@v0
        with:
          ros_distro: noetic
          github_token_bloom: ${{ secrets.GH_TOKEN_FOR_BLOOM_RELEASE }}
          github_user: jpbusch
          git_user: Jean-Pierre Busch
          git_email: jean-pierre.busch@ika.rwth-aachen.de
          release_repository_push_url: https://github.com/ika-rwth-aachen/etsi_its_messages-release.git
          open_pr: false
      - name: Release ROS 2
        uses: at-wat/bloom-release-action@v0
        with:
          ros_distro: humble jazzy
          github_token_bloom: ${{ secrets.GH_TOKEN_FOR_BLOOM_RELEASE }}
          github_user: jpbusch
          git_user: Jean-Pierre Busch
          git_email: jean-pierre.busch@ika.rwth-aachen.de
          release_repository_push_url: https://github.com/ros2-gbp/etsi_its_messages-release.git
          open_pr: false
